In [4]:
import sys, os
import numpy as np
sys.path.append("D:\\Projects\\Python\\Deep learning from scratch")
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [5]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # 用高斯分布进行初始化
    def predict(self, x):
        return np.dot(x, self.W)
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        return loss

In [6]:
net = simpleNet()
print(net.W)

[[-1.10178151 -0.76405299  2.20513124]
 [ 0.07438255 -0.10359652  1.58161107]]


In [7]:
x = np.array([0.6, 0.9])
p = net.predict(x)

In [8]:
p

array([-0.59412462, -0.55166866,  2.7465287 ])

In [9]:
np.argmax(p)

2

In [10]:
t = np.array([0, 0, 1]) # 正确解标签

In [11]:
net.loss(x, t)

0.06986500973987983

In [12]:
def f(W):
    return net.loss(x ,t)

dW = numerical_gradient(f, net.W) # 求损失函数对W的梯度

In [13]:
dW

array([[ 0.01981444,  0.0206738 , -0.04048824],
       [ 0.02972166,  0.0310107 , -0.06073236]])

In [14]:
f = lambda w: net.loss(x, t)

In [16]:
dW = numerical_gradient(f, net.W)

In [17]:
dW

array([[ 0.01981444,  0.0206738 , -0.04048824],
       [ 0.02972166,  0.0310107 , -0.06073236]])

### 神经网络的学习过程
1. 从训练数据中随机选出一部分数据，这部分数据称为mini-batch。我们的目标是减小mini-batch 的损失函数的值。
2. 为了减小mini-batch 的损失函数的值，需要求出各个权重参数的梯度。梯度表示损失函数的值减小最多的方向。
3. 将权重参数沿梯度方向进行微小更新。
4. 重复步骤1、步骤2、步骤3。
通过梯度下降法更新参数，不过因为这里使用的数据是随机选择的mini batch 数据，所以又称为随机梯度下降法（stochastic gradient descent）。