In [2]:
import numpy as np
l = [1, 2, 3, 4, 5]
t = np.zeros((len(l), 10))

In [3]:
t

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
list(enumerate(t))

[(0, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
 (1, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
 (2, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
 (3, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])),
 (4, array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))]

In [5]:
for idx, row in enumerate(t):
    row[l[idx]] = 1

In [6]:
t

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [15]:
y = np.zeros((5,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
y[np.arange(5), [2, 7, 0, 9, 4]]

IndexError: index 7 is out of bounds for axis 1 with size 5

In [1]:
import sys, os


In [2]:
os.path

<module 'ntpath' from 'D:\\IDE\\Anaconda\\lib\\ntpath.py'>

In [3]:
os.path.append()

AttributeError: module 'ntpath' has no attribute 'append'

In [4]:
os.pardir

'..'

In [6]:
sys.path.append(os.pardir)

In [7]:
print(sys.path)

['', 'D:\\Projects\\Python\\Deep learning from scratch\\Ch4. Learning of Neural Network', 'D:\\IDE\\Anaconda\\python37.zip', 'D:\\IDE\\Anaconda\\DLLs', 'D:\\IDE\\Anaconda\\lib', 'D:\\IDE\\Anaconda', 'D:\\IDE\\Anaconda\\lib\\site-packages', 'D:\\IDE\\Anaconda\\lib\\site-packages\\win32', 'D:\\IDE\\Anaconda\\lib\\site-packages\\win32\\lib', 'D:\\IDE\\Anaconda\\lib\\site-packages\\Pythonwin', 'D:\\IDE\\Anaconda\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\HaoyuPan\\.ipython', '..', '..']
