## 输出函数设计
### softmax
恒等函数：恒等函数会将输入按原样输出，对于输入的信息，不加以任何改动地直接输出。
![](../img/identity.png)
softmax函数：
$$
    y_k = \frac{\exp(a_k)}{\sum^n_{i=1}\exp(a_i)}
$$
第k个神经元的输出是$y_k$，n表示n个输出神经元。分母是输入，即上层输出a_k；分母是该层所有神经元的输入和。
![](../img/softmax.png)

In [3]:
import numpy as np

def softmax(a):
    exp_a = np.exp(a) # 对a中每个元素求e的指数
    sum_exp_a = np.sum(exp_a) # 计算a的指数和
    return exp_a/sum_exp_a

a = np.array([1.0, 0.5, 4.0])
softmax(a)

array([0.0460998 , 0.02796094, 0.92593926])

### softmax的改进
上面的softmax函数的实现虽然正确描述了式，但在计算机的运算上有一定的缺陷。这个缺陷就是溢出问题。softmax函数的实现中要进行指数函数的运算，但是此时指数函数的值很容易变得非常大。所以一般用以下方式改进softmax函数：
$$\begin{aligned}
    y_k &= \frac{C\exp(a_k)}{C\sum^n_{i=1}\exp(a_i)} \\
    &=\frac{ C\exp(a_k)}{C\sum^n_{i=1}\exp(a_i)} \\
    &=\frac{ \exp(a_k+\log C)}{C\sum^n_{i=1}\exp(a_i+\log C)}
\end{aligned}$$
这里的$\log{C}$可以使用任何值，但是为了防止溢出，一般会使用输入信号中的最大值

In [4]:
a = np.array([1010, 1000, 990])
np.exp(a)/np.sum(np.exp(a))

D:\IDE\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [5]:
c = np.max(a)
a -= c
a

array([  0, -10, -20])

In [6]:
np.exp(a)/np.sum(np.exp(a))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [10]:
def softmax(a):
    a -= np.max(a)
    exp_a = np.exp(a) # 对a中每个元素求e的指数
    sum_exp_a = np.sum(exp_a) # 计算a的指数和
    return exp_a/sum_exp_a

In [11]:
y = softmax(a)
y

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [12]:
np.sum(y)

1.0

softmax函数的输出是0.0 到1.0之间的实数。并且，softmax函数的输出值的总和是1。

上面的例子可以解释成y[0]的概率是0.018（1.8%），y[1]的概率是0.245（24.5%），y[2]的概率是0.737（73.7%）