In [1]:
 import numpy as np

In [5]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [6]:
y = np.array([2.0, 4.0, 6.0])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [7]:
print(x/2.0)

[0.5 1.  1.5]


In [12]:
A = np.array([[1.0, 2.0],[3.0,4.0]])
print(A)
print(A.shape)
print(A.dtype)

[[1. 2.]
 [3. 4.]]
(2, 2)
float64


In [13]:
print(A+1) # 广播

[[2. 3.]
 [4. 5.]]


In [16]:
print(A[0,1]) # =A[0][1]
print(A[np.array([0,1])]) #获取A中索引为0和1的元素

2.0
[[1. 2.]
 [3. 4.]]


In [18]:
A = A.flatten() # 将A转换为一维数组，注意要赋值给A
print(A)

[1. 2. 3. 4.]


In [20]:
X = np.array([20, 25, 50, 55])
print(X)
print(X>25)
print(X[X>25])

[20 25 50 55]
[False False  True  True]
[50 55]


TypeError: data type not understood